(setq inhibit-startup-message t)
(show-paren-mode t)
(load-theme 'wombat)
(transient-mark-mode t)
(setq x-select-enable-clipboard t)
(setq menu-bar-mode nil)
(setq tool-bar-mode nil)
(setq kill-whole-line t)

(provide 'visual-config)
